version: '2'

services:
  dninja_node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dninja_node
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./srv:/srv_dninja
    networks:
      - dninja

networks:
  dninja:
